### ISSUE TITLE
Allow UDL to use parser from built in language.

### ISSUE THREAD

**Issue by dail8859** [dail8859/DoxyIt#5]

**Comment by vinsworldcom** [comment]
This "enhancement" looks oooold (2013), but I'll poke it.  I use(d) Perl quite extensively and just the active commenting feature alone for Perl is great and would look much like Python.  I set up a "UDL" in DoxyIt called "Perl" without having an actual User Defined Language for Perl (since N++ already has a Perl language) and with the following diff and recompile, it worked:

diff --git a/src/Parsers/Parsers.cpp b/src/Parsers/Parsers.cpp
index 4d6cf06..8ca4dec 100644
--- a/src/Parsers/Parsers.cpp
+++ b/src/Parsers/Parsers.cpp
@@ -98,6 +98,28 @@ const Parser *getCurrentParser(bool update)

                        free(name);
                }
+        else if (lang_type == L_PERL)
+        {
+                       wchar_t *name = NULL;
+                       size_t len = 0;
+
+                       len = SendNpp(NPPM_GETLANGUAGENAME, lang_type, NULL) + 1;
+                       name = (wchar_t *) malloc(sizeof(wchar_t) * len);
+                       SendNpp(NPPM_GETLANGUAGENAME, lang_type, (LPARAM) name);
+
+                       for(auto const &p : parsers)
+                       {
+                               // Use [0] 'cause PERL
+                               if(p.language_name == &name[0])
+                               {
+                                       current = &p;
+                                       free(name);
+                                       return current;
+                               }
+                       }
+
+                       free(name);
+        }
                else
                {
                        for(auto const &p : parsers)

I wonder for more general use, the "else if" could match any N++ language type and if the user has defined a DoxyIt parser for it, it would work.  Again, the active commenting feature is the best!

Cheers.

**Comment by vinsworldcom** [comment]
How about this one more generic:

Patch for src/Parsers/Parsers.cpp:
```
diff --git a/src/Parsers/Parsers.cpp b/src/Parsers/Parsers.cpp
index 4d6cf06..d1df13e 100644
--- a/src/Parsers/Parsers.cpp
+++ b/src/Parsers/Parsers.cpp
@@ -110,6 +110,26 @@ const Parser *getCurrentParser(bool update)
                        }
                }

+               wchar_t *name = NULL;
+               size_t len = 0;
+
+               len = SendNpp(NPPM_GETLANGUAGENAME, lang_type, NULL) + 1;
+               name = (wchar_t *) malloc(sizeof(wchar_t) * len);
+               SendNpp(NPPM_GETLANGUAGENAME, lang_type, (LPARAM) name);
+
+               for(auto const &p : parsers)
+               {
+                       // Use [0] to match any build-in language
+                       if(p.language_name == &name[0])
+                       {
+                               current = &p;
+                               free(name);
+                               return current;
+                       }
+               }
+
+               free(name);
+
                // Parser wasn't found for current language
                current = nullptr;
        }
```

And added to my DoxyIt.ini:
```
[Perl]
doc_start="## "
doc_line_="#  "
doc_end__="#  "
command_prefix="@"
file_format="\r\n$@file $FILENAME\r\n$@brief $(Brief description)\r\n"
function_format="\r\n$@brief $(Brief description)\r\n\r\n$@param [in] theParam $(Description)\r\n$@return $(Return description)\r\n"
[PowerShell]
doc_start="## "
doc_line_="#  "
doc_end__="#  "
command_prefix="@"
file_format="\r\n$@file $FILENAME\r\n$@brief $(Brief description)\r\n"
function_format="\r\n$@brief $(Brief description)\r\n\r\n$@param [in] theParam $(Description)\r\n$@return $(Return description)\r\n"
[Batch]
doc_start="REM "
doc_line_="REM "
doc_end__="REM "
command_prefix="@"
file_format="\r\n$@file $FILENAME\r\n$@brief $(Brief description)\r\n"
function_format="\r\n$@brief $(Brief description)\r\n\r\n$@param [in] theParam $(Description)\r\n$@return $(Return description)\r\n"
[External]
Perl=
PowerShell=
Batch=
```

And now the active commenting is working for me in Windows Batch, Windows PowerShell and Perl!

Cheers.
